--drop table raw_currency_exchange
create table raw_currency_exchange (
	 id int generated by default as identity primary key
	,currency varchar
	,local_to_AUD varchar
	,AUD_to_local varchar
	,currency_code varchar
	,synched_at timestamp not null default now()
	,currency_rate_id int
);

create index raw_currency_exchange_currency_code_idx on raw_currency_exchange using btree (upper(currency_code));
create index raw_currency_exchange_currency_rate_id_idx on raw_currency_exchange using btree (currency_rate_id);