--drop table raw_client_customer 
create table raw_client_customer (
	 id int generated by default as identity primary key
	,client varchar
	,address1 varchar
	,address2 varchar
	,address3 varchar
	,city varchar
	,state varchar
	,zipcode varchar
	,country varchar
	,primary_location varchar
	,phone varchar
	,fax varchar
	,currency varchar
	,primary_currency varchar
	,contact varchar
	,primary_contact varchar
	,direct_phone varchar
	,mobile varchar	
	,email varchar
	,synched_at timestamp not null default now()
	,client_id int
	,location_id int
	,contact_id int
);


create index raw_client_customer_client_idx on raw_client_customer using btree (lower(client));
create index raw_client_customer_contact_idx on raw_client_customer using btree (lower(contact));
create index raw_client_customer_currency_idx on raw_client_customer using btree (upper(currency));
create index raw_client_customer_client_id_idx on raw_client_customer using btree (client_id);
create index raw_client_customer_location_id_idx on raw_client_customer using btree (location_id);
create index raw_client_customer_contact_id_idx on raw_client_customer using btree (contact_id);
