-- drop table clients cascade;

create table clients (
	 id int generated by default as identity primary key
	,client_name varchar
	,primary_location_id int
	,primary_contact_id int
	,primary_currency_code varchar(3) default 'AUD'
	,created_at timestamp not null default now()
	,updated_at timestamp null
	,synched_at timestamp not null default now()
);

-- INDECIES
create index clients_client_name_idx on clients using btree (lower(client_name));
create index clients_primary_location_id_idx on clients using btree (primary_location_id);
create index clients_primary_contact_id_idx on clients using btree (primary_contact_id);
create index clients_primary_currency_code_idx on clients using btree (primary_currency_code);
create index clients_created_at_updated_at_idx on clients using btree (created_at,updated_at);

-- FOREIGN KEYS
alter table clients
    add constraint fk_primary_contact_clients
		foreign key (primary_contact_id) 
		references contacts (id);
alter table clients
    add constraint fk_primary_location_clients
		foreign key (primary_location_id) 
		references locations (id);
alter table clients
    add constraint fk_primary_currency_code_clients
		foreign key (primary_currency_code) 
		references locations (id);		
