create table currency_rates (
	 id int generated by default as identity primary key
	,currency varchar(50) not null default '>CURRENCY<'
	,currency_code varchar(10) not null default '>CODE<'
	,currency_to_AUD float not null default 1
	,AUD_to_currency float not null default 1
	,synched_at timestamp not null default now()

);

create index currency_rates_currency_code_idx on locations using btree (upper(currency_code));