create table raw_client_customer (
	 id int generated by default as identity primary key
	,client varchar
	,address1 varchar
	,address2 varchar
	,address3 varchar
	,city varchar
	,state varchar
	,zipcode varchar
	,country varchar
	,phone varchar
	,fax varchar
	,currency varchar
	,contact varchar
	,direct_phone varchar
	,mobile varchar	
	,email varchar
	,synched_at timestamp not null default now()
);


create index raw_client_customer_client_idx on raw_client_customer using btree (lower(client));
create index raw_client_customer_contact_idx on raw_client_customer using btree (lower(contact));
create index raw_client_customer_currency_idx on raw_client_customer using btree (upper(currency));

