create table clients (
	 id int GENERATED BY DEFAULT AS IDENTITY PRIMARY key
	,client_name varchar
	,address_prefix varchar(255)
	,address_street varchar(255)
	,address_location varchar(100)
	,address_state varchar(50)
	,address_country varchar(50) default 'Australia'
	,currency_code varchar(3) default 'AUD'
	,created_at timestamp default now()
	,updated_at timestamp
);

create index client_name_idx on clients using btree (lower(client_name));
create index address_idx on clients using btree (lower(address_prefix),lower(address_street),lower(address_location),lower(address_state),lower(address_country));
create index currency_code_idx on clients using btree (currency_code);
create index created_at_updated_at_idx on clients using btree (created_at,updated_at);



